BINDING_HEADER_GHOST = "Ghost";
BINDING_NAME_ghostOpenHide = "View frame";
BINDING_NAME_ghostButton1 = "Button 1";
BINDING_NAME_ghostButton2 = "Button 2";
BINDING_NAME_ghostButton3 = "Button 3";
BINDING_NAME_ghostButton4 = "Button 4";
BINDING_NAME_ghostButton5 = "Button 5";
BINDING_NAME_ghostButton6 = "Button 6";
BINDING_NAME_ghostButton7 = "Button 7";
BINDING_NAME_ghostButton8 = "Button 8";
BINDING_NAME_ghostButton9 = "Button 9";
BINDING_NAME_ghostButton10 = "Button 10";
BINDING_NAME_ghostButton11 = "Button 11";
BINDING_NAME_ghostButton12 = "Button 12";
BINDING_NAME_ghostButton13 = "Button 13";
BINDING_NAME_ghostButton14 = "Button 14";
BINDING_NAME_ghostButton15 = "Button 15";
BINDING_NAME_ghostButton16 = "Button 16";
BINDING_NAME_ghostButton17 = "Button 17";
BINDING_NAME_ghostButton18 = "Button 18";
BINDING_NAME_ghostButton19 = "Button 19";
BINDING_NAME_ghostButton20 = "Button 20";
BINDING_NAME_ghostButton21 = "Button 21";
BINDING_NAME_ghostButton22 = "Button 22";
BINDING_NAME_ghostButton23 = "Button 23";
BINDING_NAME_ghostButton24 = "Button 24";
BINDING_NAME_ghostButton25 = "Button 25";

ghostText = {};

ghostText['loaded'] = "Ghost loaded";
ghostText['addKeyHelp'] = "Ghost: No key bound to open Ghost frame, please set a key at 'Key Bindings' in World of Warcraft menu.";
ghostText['slashHelp'] = "Ghost: Usage - /ghost [ lock | reload | reset | scale | text ]";
ghostText['buttonLocked'] = "Ghost: buttons locked";
ghostText['buttonUnlocked'] = "Ghost: buttons unlocked";
ghostText['frameLocked'] = "Ghost: frame locked";
ghostText['frameUnlocked'] = "Ghost: frame unlocked";
ghostText['lockHelp'] = "Ghost: Usage - /ghost lock [ button | frame ]";
ghostText['resetLock'] = "Ghost: frame and buttons are reseted to default (locked)";
ghostText['resetScale'] = "Ghost: Scale is reseted to default (1)";
ghostText['resetText'] = "Ghost: binding text is reseted to default (visible)"
ghostText['resetHelp'] = "Ghost: Usage - /ghost reset [ lock | scale | text ]";
ghostText['setScale'] = "Ghost: frame scale is set to ";
ghostText['scaleHelp'] = "Ghost: Usage - /ghost scale [ 0 - 2.5 ]";
ghostText['ShowText'] = "Ghost: Show button bindings"
ghostText['ShowNoText'] = "Ghost: Hide button bindings"

ghostText['scale'] = "scale";
ghostText['reset'] = "reset";
ghostText['lock'] = "lock";
ghostText['text'] = "text"; 
